version: "3.9"
services:
    rabbitmq:
        container_name: rabbitmq_container
        image: rabbitmq:3.13-rc-management-alpine
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: jobber
            RABBITMQ_DEFAULT_PASS: secret
        ports:
            # AMQP protocol port
            - "5672:5672"
            # Management UI
            - "15672:15672"

    redis:
        container_name: redis_container
        image: redis:alpine
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --loglevel warning

    postgres:
        container_name: postgres_container
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: jobber
            POSTGRES_PASSWORD: secret
            POSTGRES_MULTIPLE_DATABASES: jobber_auth,jobber_reviews
        ports:
            - "5432:5432"
        volumes:
            - ./11-configs/pg-init-scripts:/docker-entrypoint-initdb.d

    mongodb:
        container_name: mongodb_container
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017

    elasticsearch:
        container_name: elasticsearch_container
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
        restart: always
        labels:
            co.elastic.logs/enabled: false
        environment:
            ES_JAVA_OPTS: -Xmx1g -Xms1g
            bootstrap.memory_lock: "true"
            discovery.type: single-node
            network.host: 0.0.0.0
            transport.host: 127.0.0.1
            http.host: 0.0.0.0
            xpack.security.enabled: "true"
            xpack.security.authc.api_key.enabled: "true"
            xpack.monitoring.collection.enabled: "true"
            xpack.security.enrollment.enabled: "true"
            xpack.security.authc.token.enabled: "true"
            ELASTIC_PASSWORD: secret
        ports:
            - 9300:9300
            - 9200:9200

    kibana:
        container_name: kibana_container
        image: docker.elastic.co/kibana/kibana:8.11.0
        restart: always
        environment:
            - ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]
            - ELASTICSEARCH_USERNAME=kibana_system
            - ELASTICSEARCH_PASSWORD=kibana
            - ELASTICSEARCH_SERVICEACCOUNT_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL2pvYmJlci1raWJhbmE6NXVRNkZnU29RZFNVMy1ock5lWmlZQQ
            - XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]
        ports:
            - 5601:5601
        # networks:
        #     - elastic
        volumes:
            - ./11-configs/kibana.yml/:/usr/share/kibana/config/kibana.yml:ro
        depends_on:
            - elasticsearch

    filebeat:
        container_name: filebeat_container
        image: docker.elastic.co/beats/filebeat:8.11.0
        restart: always
        environment:
            - ELASTICSEARCH_HOSTS=elasticsearch_container
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=secret
        labels:
            - "co.elastic.logs/enabled=false"
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
            - type: bind
              source: /var/lib/docker
              target: /var/lib/docker
            - ./11-configs/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
        command: filebeat -e -strict.perms=false
        user: root

    heartbeat:
        container_name: heartbeat_container
        image: docker.elastic.co/beats/heartbeat:8.11.0
        restart: always
        user: root
        hostname: heartbeat
        environment:
            - ELASTICSEARCH_HOSTS=elasticsearch_container
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=secret
        cap_add:
            - NET_RAW
        volumes:
            - ./11-configs/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
        command: ["--strict.perms=false"]
        depends_on:
            - elasticsearch

    apmServer:
        container_name: apm_server_container
        image: docker.elastic.co/apm/apm-server:8.11.0
        ports:
            - 8200:8200
        environment:
            - ELASTICSEARCH_HOSTS=elasticsearch_container
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=secret
        volumes:
            - ./11-configs/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
        command: >
            apm-server -e
                -E apm-server.rum.enabled=true
                -E setup.kibana.host=kibana_container:5601
                -E setup.template.settings.index.number_of_replicas=0
                -E apm-server.kibana.enabled=true
                -E apm-server.kibana.host=kibana_container:5601
                -E apm-server.kibana.protocol=http
                -E strict.perms=false
                -E apm-server.auth.anonymous.enabled=true

    gateway:
        container_name: gateway_container
        build:
            context: ./1-gateway-service
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - 4000:4000
        labels:
            co.elastic.logs/enabled: true
            co.elastic.logs/json.keys_under_root: true
            co.elastic.logs/json.overwrite_keys: true
            co.elastic.logs/json.add_error_key: true
            co.elastic.logs/json.expand_keys: true
        environment:
            ENABLE_APM: 0
            APP_ENV: production
            LOG_LEVEL: debug
            GATEWAY_JWT_TOKEN: f2cc0c74dfb480f1a58c649d83f40f69725645371e6a6e98b53adef87fd6eb79
            JWT_TOKEN: fcdbf0d9ddaf6ce8334e9ca7547e026271987e9e0f36c8ec9737c43a38ffd362
            SECRET_KEY_ONE: c909104df830fcc73c705647d731b8cbec080e65d091350dd3bfa5cc43ccaf69
            SECRET_KEY_TWO: 45f2b0a82fb827342fd022507f64e9c7fb81a0e9421b10ba094e1903f8bfcb8e
            CLIENT_URL: http://localhost:3000
            AUTH_ENDPOINT: auth:4002
            USERS_ENDPOINT: users:4003
            GIG_ENDPOINT: gig:4004
            MESSAGE_ENDPOINT: chat:4005
            ORDER_ENDPOINT: order:4006
            REVIEW_ENDPOINT: review:4007
            REDIS_HOST: redis://redis_container:6379
            ELASTIC_SEARCH_URL: http://elastic:secret@elasticsearch_container:9200
            ELASTIC_APM_SERVER_URL: http://apm_server_container:8200
            ELASTIC_APM_SECRET_TOKEN:
            ELASTIC_APM_SERVICE_NAME: Jobber-Gateway
            ELASTIC_APM_ACTIVE: true

    notification:
        container_name: notification_container
        build:
            context: ./2-notification-service
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - 5001:5001
        labels:
            co.elastic.logs/enabled: true
            co.elastic.logs/json.keys_under_root: true
            co.elastic.logs/json.overwrite_keys: true
            co.elastic.logs/json.add_error_key: true
            co.elastic.logs/json.expand_keys: true
        environment:
            ENABLE_APM: 0
            APP_ENV: production
            LOG_LEVEL: debug
            CLIENT_URL: http://localhost:3000
            RABBITMQ_ENDPOINT: amqp://jobber:secret@rabbitmq:5672
            SENDER_EMAIL: magdalena.mccullough44@ethereal.email
            SENDER_EMAIL_PASSWORD: 3G47bzyZbJDSkHqn6z
            ELASTIC_SEARCH_URL: http://localhost:9200
            ELASTIC_APM_SERVER_URL: http://apm_server_container:8200
            ELASTIC_APM_SECRET_TOKEN:
            ELASTIC_APM_SERVICE_NAME: Jobber-Notification
            ELASTIC_APM_ACTIVE: true

    auth:
        container_name: auth_container
        build:
            context: ./3-auth-service
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - 4002:4002
            - 5002:5002
        labels:
            co.elastic.logs/enabled: true
            co.elastic.logs/json.keys_under_root: true
            co.elastic.logs/json.overwrite_keys: true
            co.elastic.logs/json.add_error_key: true
            co.elastic.logs/json.expand_keys: true
        environment:
            ENABLE_APM: 0
            GATEWAY_JWT_TOKEN: f2cc0c74dfb480f1a58c649d83f40f69725645371e6a6e98b53adef87fd6eb79
            JWT_TOKEN: fcdbf0d9ddaf6ce8334e9ca7547e026271987e9e0f36c8ec9737c43a38ffd362
            APP_ENV: production
            LOG_LEVEL: debug
            CLIENT_URL: http://localhost:3000
            API_GATEAWY_URL: http://localhost:4000
            RABBITMQ_ENDPOINT: amqp://jobber:secret@rabbitmq:5672
            DB_URI: postgres://jobber:secret@postgres_container:5432/jobber_auth
            DB_NAME: jobber_auth
            CLOUD_NAME: dymqp19df
            CLOUD_API_KEY: "931325755632488"
            CLOUD_API_SECRET: l846TZNiXes1lVJ_MTEUdMhYC6U
            ELASTIC_SEARCH_URL: http://elastic:secret@elasticsearch_container:9200
            ELASTIC_APM_SERVER_URL: http://apm_server_container:8200
            ELASTIC_APM_SECRET_TOKEN:
            ELASTIC_APM_SERVICE_NAME: Jobber-Auth
            ELASTIC_APM_ACTIVE: true

    users:
        container_name: users_container
        build:
            context: ./4-users-service
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - 4003:4003
            - 5003:5003
        labels:
            co.elastic.logs/enabled: true
            co.elastic.logs/json.keys_under_root: true
            co.elastic.logs/json.overwrite_keys: true
            co.elastic.logs/json.add_error_key: true
            co.elastic.logs/json.expand_keys: true
        environment:
            ENABLE_APM: 0
            GATEWAY_JWT_TOKEN: f2cc0c74dfb480f1a58c649d83f40f69725645371e6a6e98b53adef87fd6eb79
            JWT_TOKEN: fcdbf0d9ddaf6ce8334e9ca7547e026271987e9e0f36c8ec9737c43a38ffd362
            APP_ENV: production
            LOG_LEVEL: debug
            CLIENT_URL: http://localhost:3000
            API_GATEAWY_URL: http://localhost:4000
            RABBITMQ_ENDPOINT: amqp://jobber:secret@rabbitmq:5672
            DB_URI: mongodb://mongodb_container:27017/
            DB_NAME: Jobber
            REDIS_HOST: redis://redis_container:6379
            CLOUD_NAME: dymqp19df
            CLOUD_API_KEY: "931325755632488"
            CLOUD_API_SECRET: l846TZNiXes1lVJ_MTEUdMhYC6U
            ELASTIC_SEARCH_URL: http://elastic:secret@elasticsearch_container:9200
            ELASTIC_APM_SERVER_URL: http://apm_server_container:8200
            ELASTIC_APM_SECRET_TOKEN:
            ELASTIC_APM_SERVICE_NAME: Jobber-Users
            ELASTIC_APM_ACTIVE: true

    gig:
        container_name: gig_container
        build:
            context: ./5-gig-service
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - 4004:4004
            - 5004:5004
        labels:
            co.elastic.logs/enabled: true
            co.elastic.logs/json.keys_under_root: true
            co.elastic.logs/json.overwrite_keys: true
            co.elastic.logs/json.add_error_key: true
            co.elastic.logs/json.expand_keys: true
        environment:
            ENABLE_APM: 0
            GATEWAY_JWT_TOKEN: f2cc0c74dfb480f1a58c649d83f40f69725645371e6a6e98b53adef87fd6eb79
            JWT_TOKEN: fcdbf0d9ddaf6ce8334e9ca7547e026271987e9e0f36c8ec9737c43a38ffd362
            APP_ENV: production
            LOG_LEVEL: debug
            CLIENT_URL: http://localhost:3000
            API_GATEAWY_URL: http://localhost:4000
            RABBITMQ_ENDPOINT: amqp://jobber:secret@rabbitmq:5672
            DB_URI: mongodb://mongodb_container:27017/
            DB_NAME: Jobber
            REDIS_HOST: redis://redis_container:6379
            CLOUD_NAME: dymqp19df
            CLOUD_API_KEY: "931325755632488"
            CLOUD_API_SECRET: l846TZNiXes1lVJ_MTEUdMhYC6U
            ELASTIC_SEARCH_URL: http://elastic:secret@elasticsearch_container:9200
            ELASTIC_APM_SERVER_URL: http://apm_server_container:8200
            ELASTIC_APM_SECRET_TOKEN:
            ELASTIC_APM_SERVICE_NAME: Jobber-Gig
            ELASTIC_APM_ACTIVE: true

    chat:
        container_name: chat_container
        build:
            context: ./6-chat-service
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - 4005:4005
            - 5005:5005
        labels:
            co.elastic.logs/enabled: true
            co.elastic.logs/json.keys_under_root: true
            co.elastic.logs/json.overwrite_keys: true
            co.elastic.logs/json.add_error_key: true
            co.elastic.logs/json.expand_keys: true
        environment:
            ENABLE_APM: 0
            GATEWAY_JWT_TOKEN: f2cc0c74dfb480f1a58c649d83f40f69725645371e6a6e98b53adef87fd6eb79
            JWT_TOKEN: fcdbf0d9ddaf6ce8334e9ca7547e026271987e9e0f36c8ec9737c43a38ffd362
            APP_ENV: production
            LOG_LEVEL: debug
            CLIENT_URL: http://localhost:3000
            API_GATEAWY_URL: http://localhost:4000
            RABBITMQ_ENDPOINT: amqp://jobber:secret@rabbitmq:5672
            DB_URI: mongodb://mongodb_container:27017/
            DB_NAME: Jobber
            REDIS_HOST: redis://redis_container:6379
            CLOUD_NAME: dymqp19df
            CLOUD_API_KEY: "931325755632488"
            CLOUD_API_SECRET: l846TZNiXes1lVJ_MTEUdMhYC6U
            ELASTIC_SEARCH_URL: http://elastic:secret@elasticsearch_container:9200
            ELASTIC_APM_SERVER_URL: http://apm_server_container:8200
            ELASTIC_APM_SECRET_TOKEN:
            ELASTIC_APM_SERVICE_NAME: Jobber-Chat
            ELASTIC_APM_ACTIVE: true

    order:
        container_name: order_container
        build:
            context: ./7-order-service
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - 4006:4006
            - 5006:5006
        labels:
            co.elastic.logs/enabled: true
            co.elastic.logs/json.keys_under_root: true
            co.elastic.logs/json.overwrite_keys: true
            co.elastic.logs/json.add_error_key: true
            co.elastic.logs/json.expand_keys: true
        environment:
            ENABLE_APM: 0
            GATEWAY_JWT_TOKEN: f2cc0c74dfb480f1a58c649d83f40f69725645371e6a6e98b53adef87fd6eb79
            JWT_TOKEN: fcdbf0d9ddaf6ce8334e9ca7547e026271987e9e0f36c8ec9737c43a38ffd362
            APP_ENV: production
            LOG_LEVEL: debug
            CLIENT_URL: http://localhost:3000
            API_GATEAWY_URL: http://localhost:4000
            RABBITMQ_ENDPOINT: amqp://jobber:secret@rabbitmq:5672
            STRIPE_API_KEY: sk_test_51Omds7KRzUOzFkEpe6eCWyuG4Ehraq6gmYB77F73zqDIVWJui9BHeOEQZDMrnrWUBPcreSRdMCgH6XvWC6BwroAh00F9WAT99g
            DB_URI: mongodb://mongodb_container:27017/
            DB_NAME: Jobber
            REDIS_HOST: redis://redis_container:6379
            CLOUD_NAME: dymqp19df
            CLOUD_API_KEY: 931325755632488
            CLOUD_API_SECRET: l846TZNiXes1lVJ_MTEUdMhYC6U
            ELASTIC_SEARCH_URL: http://elastic:secret@elasticsearch_container:9200
            ELASTIC_APM_SERVER_URL: http://apm_server_container:8200
            ELASTIC_APM_SECRET_TOKEN:
            ELASTIC_APM_SERVICE_NAME: Jobber-Order
            ELASTIC_APM_ACTIVE: false

    review:
        container_name: review_container
        build:
            context: ./8-review-service
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - 4007:4007
            - 5007:5007
        labels:
            co.elastic.logs/enabled: true
            co.elastic.logs/json.keys_under_root: true
            co.elastic.logs/json.overwrite_keys: true
            co.elastic.logs/json.add_error_key: true
            co.elastic.logs/json.expand_keys: true
        environment:
            ENABLE_APM: 0
            GATEWAY_JWT_TOKEN: f2cc0c74dfb480f1a58c649d83f40f69725645371e6a6e98b53adef87fd6eb79
            JWT_TOKEN: fcdbf0d9ddaf6ce8334e9ca7547e026271987e9e0f36c8ec9737c43a38ffd362
            APP_ENV: production
            LOG_LEVEL: debug
            CLIENT_URL: http://localhost:3000
            API_GATEAWY_URL: http://localhost:4000
            RABBITMQ_ENDPOINT: amqp://jobber:secret@rabbitmq:5672
            DB_URI: postgres://jobber:secret@postgres_container:5432/jobber_reviews
            DB_NAME: jobber_reviews
            ELASTIC_SEARCH_URL: http://elastic:secret@elasticsearch_container:9200
            ELASTIC_APM_SERVER_URL: http://localhost:8200
            ELASTIC_APM_SECRET_TOKEN:
            ELASTIC_APM_SERVICE_NAME: Jobber-Review
            ELASTIC_APM_ACTIVE: false
