// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: proto/auth/search.proto

package auth

import (
	gig "github.com/thetherington/jobber-common/protogen/go/gig"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchQuery   string         `protobuf:"bytes,1,opt,name=SearchQuery,json=searchQuery,proto3" json:"SearchQuery,omitempty"`
	PaginateProps *PaginateProps `protobuf:"bytes,2,opt,name=PaginateProps,json=paginateProps,proto3,oneof" json:"PaginateProps,omitempty"`
	DeliveryTime  *string        `protobuf:"bytes,3,opt,name=DeliveryTime,json=deliveryTime,proto3,oneof" json:"DeliveryTime,omitempty"`
	Min           *float64       `protobuf:"fixed64,4,opt,name=Min,json=min,proto3,oneof" json:"Min,omitempty"`
	Max           *float64       `protobuf:"fixed64,5,opt,name=Max,json=max,proto3,oneof" json:"Max,omitempty"`
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_search_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_search_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *SearchRequest) GetPaginateProps() *PaginateProps {
	if x != nil {
		return x.PaginateProps
	}
	return nil
}

func (x *SearchRequest) GetDeliveryTime() string {
	if x != nil && x.DeliveryTime != nil {
		return *x.DeliveryTime
	}
	return ""
}

func (x *SearchRequest) GetMin() float64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *SearchRequest) GetMax() float64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

type GetGigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
}

func (x *GetGigRequest) Reset() {
	*x = GetGigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_search_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGigRequest) ProtoMessage() {}

func (x *GetGigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_search_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGigRequest.ProtoReflect.Descriptor instead.
func (*GetGigRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_search_proto_rawDescGZIP(), []int{1}
}

func (x *GetGigRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PaginateProps struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=From,json=from,proto3" json:"From,omitempty"`
	Size int32  `protobuf:"varint,2,opt,name=Size,json=size,proto3" json:"Size,omitempty"`
	Type string `protobuf:"bytes,3,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
}

func (x *PaginateProps) Reset() {
	*x = PaginateProps{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_search_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginateProps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginateProps) ProtoMessage() {}

func (x *PaginateProps) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_search_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginateProps.ProtoReflect.Descriptor instead.
func (*PaginateProps) Descriptor() ([]byte, []int) {
	return file_proto_auth_search_proto_rawDescGZIP(), []int{2}
}

func (x *PaginateProps) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PaginateProps) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PaginateProps) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gig *gig.GigMessage `protobuf:"bytes,1,opt,name=Gig,json=gig,proto3" json:"Gig,omitempty"`
}

func (x *GigResponse) Reset() {
	*x = GigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_search_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GigResponse) ProtoMessage() {}

func (x *GigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_search_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GigResponse.ProtoReflect.Descriptor instead.
func (*GigResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_search_proto_rawDescGZIP(), []int{3}
}

func (x *GigResponse) GetGig() *gig.GigMessage {
	if x != nil {
		return x.Gig
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64             `protobuf:"varint,1,opt,name=Total,json=total,proto3" json:"Total,omitempty"`
	Hits  []*gig.GigMessage `protobuf:"bytes,2,rep,name=Hits,json=hits,proto3" json:"Hits,omitempty"`
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auth_search_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_search_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResponse) GetHits() []*gig.GigMessage {
	if x != nil {
		return x.Hits
	}
	return nil
}

var File_proto_auth_search_proto protoreflect.FileDescriptor

var file_proto_auth_search_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x1a,
	0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x69, 0x67, 0x2f, 0x67, 0x69, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfb, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x3e, 0x0a, 0x0d, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x70, 0x73, 0x48, 0x00, 0x52, 0x0d, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x70, 0x73, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x0c, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x15, 0x0a, 0x03, 0x4d, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x48, 0x02,
	0x52, 0x03, 0x6d, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x4d, 0x61, 0x78, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x48, 0x03, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x88, 0x01, 0x01, 0x42,
	0x10, 0x0a, 0x0e, 0x5f, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x70,
	0x73, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x54, 0x69,
	0x6d, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x4d, 0x69, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x4d,
	0x61, 0x78, 0x22, 0x1f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x47, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x4b, 0x0a, 0x0d, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x70, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x30, 0x0a, 0x0b, 0x47, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x21, 0x0a, 0x03, 0x47, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67,
	0x69, 0x67, 0x2e, 0x47, 0x69, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x67,
	0x69, 0x67, 0x22, 0x4b, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x23, 0x0a, 0x04, 0x48, 0x69,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x69, 0x67, 0x2e, 0x47,
	0x69, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x68, 0x69, 0x74, 0x73, 0x32,
	0x7d, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x34, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x47, 0x69, 0x67, 0x42, 0x79, 0x49, 0x64, 0x12, 0x13,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x69, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x09, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x47, 0x69, 0x67, 0x12, 0x13, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x39,
	0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65,
	0x74, 0x68, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x74, 0x6f, 0x6e, 0x2f, 0x6a, 0x6f, 0x62, 0x62, 0x65,
	0x72, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65,
	0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_auth_search_proto_rawDescOnce sync.Once
	file_proto_auth_search_proto_rawDescData = file_proto_auth_search_proto_rawDesc
)

func file_proto_auth_search_proto_rawDescGZIP() []byte {
	file_proto_auth_search_proto_rawDescOnce.Do(func() {
		file_proto_auth_search_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_auth_search_proto_rawDescData)
	})
	return file_proto_auth_search_proto_rawDescData
}

var file_proto_auth_search_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_auth_search_proto_goTypes = []interface{}{
	(*SearchRequest)(nil),  // 0: auth.SearchRequest
	(*GetGigRequest)(nil),  // 1: auth.GetGigRequest
	(*PaginateProps)(nil),  // 2: auth.PaginateProps
	(*GigResponse)(nil),    // 3: auth.GigResponse
	(*SearchResponse)(nil), // 4: auth.SearchResponse
	(*gig.GigMessage)(nil), // 5: gig.GigMessage
}
var file_proto_auth_search_proto_depIdxs = []int32{
	2, // 0: auth.SearchRequest.PaginateProps:type_name -> auth.PaginateProps
	5, // 1: auth.GigResponse.Gig:type_name -> gig.GigMessage
	5, // 2: auth.SearchResponse.Hits:type_name -> gig.GigMessage
	1, // 3: auth.SearchService.GetGigById:input_type -> auth.GetGigRequest
	0, // 4: auth.SearchService.SearchGig:input_type -> auth.SearchRequest
	3, // 5: auth.SearchService.GetGigById:output_type -> auth.GigResponse
	4, // 6: auth.SearchService.SearchGig:output_type -> auth.SearchResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_auth_search_proto_init() }
func file_proto_auth_search_proto_init() {
	if File_proto_auth_search_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_auth_search_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_search_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_search_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginateProps); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_search_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auth_search_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_auth_search_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_auth_search_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_search_proto_goTypes,
		DependencyIndexes: file_proto_auth_search_proto_depIdxs,
		MessageInfos:      file_proto_auth_search_proto_msgTypes,
	}.Build()
	File_proto_auth_search_proto = out.File
	file_proto_auth_search_proto_rawDesc = nil
	file_proto_auth_search_proto_goTypes = nil
	file_proto_auth_search_proto_depIdxs = nil
}
