// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (Auth, error)
	GetUserByEmail(ctx context.Context, email string) (Auth, error)
	GetUserById(ctx context.Context, id int64) (Auth, error)
	GetUserByPasswordToken(ctx context.Context, passwordResetToken pgtype.Text) (Auth, error)
	GetUserByUsername(ctx context.Context, username string) (Auth, error)
	GetUserByVerificationToken(ctx context.Context, emailVerificationToken string) (Auth, error)
	UpdateEmailVerificationToken(ctx context.Context, arg UpdateEmailVerificationTokenParams) (int64, error)
	UpdatePasswordToken(ctx context.Context, arg UpdatePasswordTokenParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateVerifyEmailField(ctx context.Context, arg UpdateVerifyEmailFieldParams) error
}

var _ Querier = (*Queries)(nil)
